import "./globals.css";
import type { Metadata } from "next";
import { roboto } from "./fonts.js";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Next 13",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${roboto.variable} }`}>
      <body>
        <header>
          <ul className="p-4 border-b-2 border-slate-500 text-right">
            <Link
              className="text-slate-700 m-4 px-4 py-2 hover:text-orange-700 border-2"
              href="/"
            >
              Home
            </Link>
            <Link
              className="text-slate-700 m-4 px-4 py-2 hover:text-orange-700 border-2"
              href="/reviews"
            >
              Reviews
            </Link>
            <Link
              className="text-slate-700 m-4 px-4 py-2 hover:text-orange-700 border-2"
              href="/about"
            >
              About
            </Link>
          </ul>
        </header>
        <div className="h-[80vh]">{children}</div>
        <footer className="p-4 text-center border-2 border-slate-700">
          Copyright Tech Co ltd
        </footer>
      </body>
    </html>
  );
}
